/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.h
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_FLEETMESSAGES_H_
#define _DDSL_FLEETMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif

#define FreeFleetData_RobotMode_Constants_MODE_IDLE 0
#define FreeFleetData_RobotMode_Constants_MODE_CHARGING 1
#define FreeFleetData_RobotMode_Constants_MODE_MOVING 2
#define FreeFleetData_RobotMode_Constants_MODE_PAUSED 3
#define FreeFleetData_RobotMode_Constants_MODE_WAITING 4
#define FreeFleetData_RobotMode_Constants_MODE_EMERGENCY 5
#define FreeFleetData_RobotMode_Constants_MODE_GOING_HOME 6
#define FreeFleetData_RobotMode_Constants_MODE_DOCKING 7
#define FreeFleetData_RobotMode_Constants_MODE_REQUEST_ERROR 8


typedef struct FreeFleetData_RobotMode
{
  uint32_t mode;
} FreeFleetData_RobotMode;



typedef struct FreeFleetData_Location
{
  int32_t sec;
  uint32_t nanosec;
  float x;
  float y;
  float yaw;
  char * level_name;
} FreeFleetData_Location;


typedef struct FreeFleetData_RobotState_path_seq
{
  uint32_t _maximum;
  uint32_t _length;
  FreeFleetData_Location *_buffer;
  bool _release;
} FreeFleetData_RobotState_path_seq;

#define FreeFleetData_RobotState_path_seq__alloc() \
((FreeFleetData_RobotState_path_seq*) dds_alloc (sizeof (FreeFleetData_RobotState_path_seq)));

#define FreeFleetData_RobotState_path_seq_allocbuf(l) \
((FreeFleetData_Location *) dds_alloc ((l) * sizeof (FreeFleetData_Location)))


typedef struct FreeFleetData_RobotState
{
  char * name;
  char * model;
  char * task_id;
  FreeFleetData_RobotMode mode;
  float battery_percent;
  FreeFleetData_Location location;
  FreeFleetData_RobotState_path_seq path;
} FreeFleetData_RobotState;



typedef struct FreeFleetData_Header
{
  uint32_t seq;
  char * frame_id;
} FreeFleetData_Header;



typedef struct FreeFleetData_RobotImage
{
  char * fleet_name;
  char * robot_name;
  FreeFleetData_Header image_header;
  uint32_t height;
  uint32_t width;
  char * encoding;
  bool is_bigendian;
  uint32_t step;
  dds_sequence_t data;
} FreeFleetData_RobotImage;



typedef struct FreeFleetData_ModeParameter
{
  char * name;
  char * value;
} FreeFleetData_ModeParameter;


typedef struct FreeFleetData_ModeRequest_parameters_seq
{
  uint32_t _maximum;
  uint32_t _length;
  FreeFleetData_ModeParameter *_buffer;
  bool _release;
} FreeFleetData_ModeRequest_parameters_seq;

#define FreeFleetData_ModeRequest_parameters_seq__alloc() \
((FreeFleetData_ModeRequest_parameters_seq*) dds_alloc (sizeof (FreeFleetData_ModeRequest_parameters_seq)));

#define FreeFleetData_ModeRequest_parameters_seq_allocbuf(l) \
((FreeFleetData_ModeParameter *) dds_alloc ((l) * sizeof (FreeFleetData_ModeParameter)))


typedef struct FreeFleetData_ModeRequest
{
  char * fleet_name;
  char * robot_name;
  FreeFleetData_RobotMode mode;
  char * task_id;
  FreeFleetData_ModeRequest_parameters_seq parameters;
} FreeFleetData_ModeRequest;


typedef struct FreeFleetData_PathRequest_path_seq
{
  uint32_t _maximum;
  uint32_t _length;
  FreeFleetData_Location *_buffer;
  bool _release;
} FreeFleetData_PathRequest_path_seq;

#define FreeFleetData_PathRequest_path_seq__alloc() \
((FreeFleetData_PathRequest_path_seq*) dds_alloc (sizeof (FreeFleetData_PathRequest_path_seq)));

#define FreeFleetData_PathRequest_path_seq_allocbuf(l) \
((FreeFleetData_Location *) dds_alloc ((l) * sizeof (FreeFleetData_Location)))


typedef struct FreeFleetData_PathRequest
{
  char * fleet_name;
  char * robot_name;
  FreeFleetData_PathRequest_path_seq path;
  char * task_id;
} FreeFleetData_PathRequest;



typedef struct FreeFleetData_DestinationRequest
{
  char * fleet_name;
  char * robot_name;
  FreeFleetData_Location destination;
  char * task_id;
} FreeFleetData_DestinationRequest;


#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FLEETMESSAGES_H_ */
